project:
  type: website
  output-dir: docs

execute: 
  cache: true
  freeze: auto
  warning: false

website:
  title: "FIP606"
  navbar:
    left:
     
      -  text: R Básico
         menu:
           - href: como instalar.qmd
             text: Como intalar o R
           - href: INSTALAR_CARREGAR.qmd
             text: Instalar e carregar Pacotes 
           - href: IMPORTAR_DADOS.qmd
             text: Como importar dados 
      
      -  text: Gráficos
         menu: 
           - href: GGPLOT.qmd
             text: Ggplot
           - href: BOXPLOT.qmd
             text: Boxplot
           - href: HISTOGRAMA.qmd
             text: Histograma
    
      - text: Estatística descritiva
        href: DESCRITIVA.qmd
        
      -  text: Estatística inferencial
         menu: 
           - href: TRANSFORMACAO.qmd
             text: Transformação
           - href: TESTET.qmd
             text: Teste T
           - href: ANOVA.qmd
             text: ANOVA
           - href: ANOVABLOCO.qmd
             text: ANOVA bloco
           - href: ANOVAFATORIAL.qmd
             text: ANOVA arranjo fatorial
           - href: REGRESSÃO.qmd
             text: Regressão linear
           - href: CORRELAÇÃO.qmd
             text: Correlação
           - href: EC50.qmd
             text: EC50
      
      - text: Mapa
        href: MAPAS.qmd    
             
    
      




format:
  html:
    fontsize: 1.1em
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    warning: false

editor: visual

